import discord
import io
from datetime import datetime
import config

async def generate_transcript(channel):
    """Generate a transcript of a ticket channel"""
    transcript_content = f"Generated by SereneEnterprise, all rights reserved (c) (Taken from Waterstone Academy)\n"
    transcript_content += f"Transcript for {channel.name}\n"
    transcript_content += f"Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
    transcript_content += "=" * 50 + "\n\n"
    
    async for message in channel.history(limit=None, oldest_first=True):
        timestamp = message.created_at.strftime('%Y-%m-%d %H:%M:%S')
        author = f"{message.author.display_name} ({message.author})"
        content = message.content if message.content else "[No text content]"
        
        # Handle embeds
        if message.embeds:
            for embed in message.embeds:
                if embed.title:
                    content += f"\n[EMBED] {embed.title}"
                if embed.description:
                    content += f"\n{embed.description}"
        
        # Handle attachments
        if message.attachments:
            for attachment in message.attachments:
                content += f"\n[ATTACHMENT] {attachment.filename}"
        
        transcript_content += f"[{timestamp}] {author}: {content}\n"
    
    # Create a file-like object
    transcript_file = io.BytesIO(transcript_content.encode('utf-8'))
    return discord.File(transcript_file, filename=f"{channel.name}-transcript.txt")

async def send_transcript(channel, closed_by, close_reason=None, open_reason=None):
    """Generate and send transcript to user and transcript channel"""
    try:
        # Get ticket owner and claimed info
        ticket_owner, claimed_by = get_ticket_info_from_channel(channel)
        
        # Debug print
        print(f"Ticket owner found: {ticket_owner}")
        print(f"Claimed by: {claimed_by}")
        
        # Extract open reason from channel history if not provided
        if not open_reason:
            open_reason = await extract_open_reason(channel)
        
        # Default reasons if still not provided
        if not close_reason:
            close_reason = "No reason provided"
        if not open_reason:
            open_reason = "No reason provided"
        
        # Send to transcript channel
        if config.TICKET_TRANSCRIPT_ID:
            transcript_channel = channel.guild.get_channel(int(config.TICKET_TRANSCRIPT_ID))
            if transcript_channel:
                embed = discord.Embed(
                    title="<:People:1446847702804598886>  Waterstone Support",
                    description=f"Transcript for **{channel.name}**",
                    color=None,
                    timestamp=datetime.utcnow()
                )
                embed.add_field(name="Ticket Creator", value=ticket_owner.mention if ticket_owner else "Unknown", inline=True)
                embed.add_field(name="Closed By", value=closed_by.mention, inline=True)
                embed.add_field(name="Channel", value=channel.name, inline=True)
                embed.add_field(name="Claimed By", value=claimed_by if claimed_by else "Unclaimed", inline=True)
                embed.add_field(name="Open Reason", value=open_reason, inline=True)
                embed.add_field(name="Close Reason", value=close_reason, inline=True)
                embed.set_image(url="https://media.discordapp.net/attachments/1353870922712354900/1437239861802303628/WSALine.png?ex=693423ad&is=6932d22d&hm=96f2ac4bdc5294f7109fc750e3225b22e73dfef514ce605c545e6dadb26ebdb4&=&format=webp&quality=lossless")
                
                # Generate transcript for the channel
                transcript_file_copy = await generate_transcript(channel)
                await transcript_channel.send(embed=embed, file=transcript_file_copy)
                print(f"Transcript sent to transcript channel")
        
        # Send to ticket creator via DM
        if ticket_owner:
            try:
                print(f"Attempting to send DM to {ticket_owner.name}...")
                dm_embed = discord.Embed(
                    title="<:People:1446847702804598886>  Your Ticket Has Been Closed",
                    color=0x2B2D31,
                    timestamp=datetime.utcnow()
                )
                dm_embed.add_field(name="Server", value=channel.guild.name, inline=True)
                dm_embed.add_field(name="Closed By", value=closed_by.display_name, inline=True)
                dm_embed.add_field(name="Channel", value=channel.name, inline=True)
                dm_embed.add_field(name="Claimed By", value=claimed_by if claimed_by else "Unclaimed", inline=True)
                dm_embed.add_field(name="Open Reason", value=open_reason, inline=True)
                dm_embed.add_field(name="Close Reason", value=close_reason, inline=True)
                dm_embed.set_image(url="https://media.discordapp.net/attachments/1353870922712354900/1437239861802303628/WSALine.png?ex=693423ad&is=6932d22d&hm=96f2ac4bdc5294f7109fc750e3225b22e73dfef514ce605c545e6dadb26ebdb4&=&format=webp&quality=lossless")
                
                # Create another copy for DM
                transcript_file_dm = await generate_transcript(channel)
                await ticket_owner.send(embed=dm_embed, file=transcript_file_dm)
                print(f"Successfully sent transcript to {ticket_owner.name}")
            except discord.Forbidden:
                print(f"Cannot send DM to {ticket_owner.name} - DMs disabled")
            except Exception as e:
                print(f"Error sending transcript to user: {e}")
        else:
            print("No ticket owner found - cannot send DM")
    
    except Exception as e:
        print(f"Error generating/sending transcript: {e}")
        import traceback
        traceback.print_exc()

async def extract_open_reason(channel):
    """Extract the opening reason from the ticket channel's history"""
    try:
        async for message in channel.history(limit=50, oldest_first=True):
            # Look for the embed that contains "Reason:" field
            if message.embeds:
                for embed in message.embeds:
                    if embed.description and "**Reason**:" in embed.description:
                        # Extract reason from description
                        lines = embed.description.split('\n')
                        for line in lines:
                            if line.startswith("**Reason**:"):
                                reason = line.replace("**Reason**:", "").strip()
                                return reason if reason else "No reason provided"
        return "No reason provided"
    except Exception as e:
        print(f"Error extracting open reason: {e}")
        return "No reason provided"

def get_ticket_info_from_channel(channel):
    """Extract ticket information from channel name and topic"""
    ticket_owner = None
    claimed_by = None
    
    # Method 1: Check channel topic for user ID (most reliable)
    if channel.topic:
        # Look for user mentions in topic
        if channel.topic.startswith("<@") and ">" in channel.topic:
            user_id = channel.topic.split(">")[0].replace("<@", "").replace("!", "")
            try:
                ticket_owner = channel.guild.get_member(int(user_id))
            except:
                pass
        
        # Get claimed info from topic
        if "Claimed by:" in channel.topic:
            claimed_by = channel.topic.split("Claimed by:")[-1].strip()
    
    # Method 2: Check channel permissions (backup method)
    if not ticket_owner:
        for member in channel.members:
            # Look for a member who has special permissions but isn't a bot
            if not member.bot:
                perms = channel.permissions_for(member)
                # Check if they have read permissions (ticket owner should have this)
                if perms.read_messages and perms.send_messages:
                    # Check if they're not a staff member (you might need to adjust this logic)
                    staff_roles = ["Staff", "Admin", "Moderator", "Support"]  # Adjust these role names
                    is_staff = any(role.name in staff_roles for role in member.roles)
                    if not is_staff:
                        ticket_owner = member
                        break
    
    # Method 3: Try to extract from channel name (least reliable)
    if not ticket_owner and channel.name.startswith("ticket-"):
        owner_name = channel.name.replace("ticket-", "").lower()
        # Try to find the user
        for member in channel.guild.members:
            if member.name.lower() == owner_name or member.display_name.lower() == owner_name:
                ticket_owner = member
                break
    
    return ticket_owner, claimed_by